### ISSUE TITLE
Download links for craptev1/crapto1 are down

### ISSUE THREAD

**Issue by WhereIsTheExit** [nfc-tools/miLazyCracker#19]
The download links for the two archives that were added in PR #14 are down for me. I don't know if this is a temporary issue. 
I could not find a convenient URL for the script online, but it seems like the sources can be found with some searching or by [asking Bla](https://github.com/aczid/crypto1_bs/issues/29).

**Comment by jtoddowen** [comment]
Edit the `wget` statements the FreshInstall shell script as follows:

```
wget -nH -nd -r -l1 -A.xz https://web.archive.org/web/20190221140240/http://www2.vaneay.fr/mifare/craptev1-v1.1.tar.xz
wget -nH -nd -r -l1 -A.xz https://web.archive.org/web/20190221140255/http://www2.vaneay.fr/mifare/crapto1-v3.3.tar.xz
```

Note: The times are off by a 15 seconds, so watch if you're typing it out.  This will download just the xz archive into the miLazyCrackerFreshInstall.sh folder (where you execute the script from).

**Comment by DavidBerdik** [comment]
I have submitted a pull request to fix this.

https://github.com/nfc-tools/miLazyCracker/pull/22

**Comment by doegox** [comment]
thanks
