### ISSUE TITLE
Segmentation Fault at line 127

### ISSUE THREAD

**Issue by d0lf99** [nfc-tools/miLazyCracker#32]
After the collecting nonces part, I always get a "line 127: segmentation fault" error, log attached.

`Collected 2989 nonces... leftover complexity 44169378568 (~2^35.36) - initializing brute-force phase...
Starting 4 threads to test 44169378568 states using 64-way bitslicing
Cracking...   0.00%/usr/local/bin/miLazyCracker: line 127:  3050 Segmentation fault      "${mycmd[@]}"
`

Anyone has any idea of what might cause this issue?

**Comment by mattiarainieri** [comment]
I have the same problem: it create a sort of loop

**Comment by ld21** [comment]
I have the same problem – why has the comment been closed?

**Comment by mattiarainieri** [comment]
@ld21 I've fixed using a x86 architecture processor; On Rapsberry or other pc arm based reports me this error
